import { GeistSans, GeistMono } from 'geist/font'; // Correct import from 'geist' package
import { headers } from 'next/headers';
import { NextRequest } from 'next/server';
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { TranslationProvider } from "./../TranslationContext";
import LoadingScreen from "./components/LoadingScreen";
import MaintenancePage from "./maintenance/page";

export const metadata = {
  title: "Inspire Group",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const headerList = await headers();
  const isNotLegalPage = headerList.get('x-not-legal') === 'true';
  const isPHCountry = headerList.get('x-ph-country') === 'true';
  const maintenanceEnvTrue = process.env.MAINTENANCE_MODE === 'true' || process.env.NEXT_PUBLIC_MAINTENANCE_MODE === 'true';
  const maintenanceEnvFalse = process.env.MAINTENANCE_MODE === 'false' || process.env.NEXT_PUBLIC_MAINTENANCE_MODE === 'false';
  const maintenanceEnabled = maintenanceEnvFalse ? false : (maintenanceEnvTrue || true);

  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <body className="antialiased min-h-screen flex flex-col" suppressHydrationWarning>
        <TranslationProvider>
          {maintenanceEnabled ? (
            <main className="flex-1">
              <MaintenancePage />
            </main>
          ) : isNotLegalPage ? (
            <main className="flex-1">{children}</main>
          ) : (
            <>
              <LoadingScreen />
              <Header />
              <main className="flex-1">{children}</main>
              <Footer />
            </>
          )}
        </TranslationProvider>
      </body>
    </html>
  );
} 